use maolan_clap::ffi::{
    CLAP_PARAM_IS_AUTOMATABLE, CLAP_PARAM_IS_ENUM, CLAP_PARAM_IS_STEPPED,
    CLAP_PARAM_REQUIRES_PROCESS,
};

crate::define_params! {
    pub enum ParamId {
        InputGain = 0,
        OutputGain = 1,
        DryGain = 2,
        WetGain = 3,
        ScMode = 4,
        Bypass = 5,
        Split1 = 6,
        Split2 = 7,
        Split3 = 8,
        B1Threshold = 9,
        B1Ratio = 10,
        B1Attack = 11,
        B1Release = 12,
        B1Knee = 13,
        B1Makeup = 14,
        B2Threshold = 15,
        B2Ratio = 16,
        B2Attack = 17,
        B2Release = 18,
        B2Knee = 19,
        B2Makeup = 20,
        B3Threshold = 21,
        B3Ratio = 22,
        B3Attack = 23,
        B3Release = 24,
        B3Knee = 25,
        B3Makeup = 26,
        B4Threshold = 27,
        B4Ratio = 28,
        B4Attack = 29,
        B4Release = 30,
        B4Knee = 31,
        B4Makeup = 32,
        Mode = 33,
        Lookahead = 34,
        ScBoost = 35,
        Topology = 36,
        Channels = 37,
        B1Range = 38,
        B2Range = 39,
        B3Range = 40,
        B4Range = 41,
        Split4 = 42,
        Split5 = 43,
        BandCount = 44,
        B5Threshold = 45,
        B5Ratio = 46,
        B5Attack = 47,
        B5Release = 48,
        B5Knee = 49,
        B5Makeup = 50,
        B5Range = 51,
        B6Threshold = 52,
        B6Ratio = 53,
        B6Attack = 54,
        B6Release = 55,
        B6Knee = 56,
        B6Makeup = 57,
        B6Range = 58,
    }
    pub const PARAMS: [ParamDef] = [
        {
            id: ParamId::InputGain,
            name: "Input Gain",
            module: "Gain",
            min: -90.0,
            max: 20.0,
            default: 0.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::OutputGain,
            name: "Output Gain",
            module: "Gain",
            min: -90.0,
            max: 20.0,
            default: 0.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::DryGain,
            name: "Dry Gain",
            module: "Mix",
            min: 0.0,
            max: 1.0,
            default: 0.0,
            step: 0.01,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::WetGain,
            name: "Wet Gain",
            module: "Mix",
            min: 0.0,
            max: 1.0,
            default: 4.0,
            step: 0.01,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::ScMode,
            name: "Sidechain Mode",
            module: "Sidechain",
            min: 0.0,
            max: 1.0,
            default: 1.0,
            step: 1.0,
            flags: ENUM_FLAGS,
        }
        {
            id: ParamId::Bypass,
            name: "Bypass",
            module: "Global",
            min: 0.0,
            max: 1.0,
            default: 0.0,
            step: 1.0,
            flags: BOOL_FLAGS,
        }
        {
            id: ParamId::Split1,
            name: "Split 1",
            module: "Crossover",
            min: 20.0,
            max: 500.0,
            default: 120.0,
            step: 1.0,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::Split2,
            name: "Split 2",
            module: "Crossover",
            min: 200.0,
            max: 4000.0,
            default: 1000.0,
            step: 1.0,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::Split3,
            name: "Split 3",
            module: "Crossover",
            min: 1500.0,
            max: 18000.0,
            default: 6000.0,
            step: 1.0,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B1Threshold,
            name: "Band 1 Threshold",
            module: "Band 1",
            min: -52.5,
            max: 30.0,
            default: -3.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B1Ratio,
            name: "Band 1 Ratio",
            module: "Band 1",
            min: 1.0,
            max: 100.0,
            default: 4.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B1Attack,
            name: "Band 1 Attack",
            module: "Band 1",
            min: 0.0,
            max: 2000.0,
            default: 20.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B1Release,
            name: "Band 1 Release",
            module: "Band 1",
            min: 0.0,
            max: 5000.0,
            default: 100.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B1Knee,
            name: "Band 1 Knee",
            module: "Band 1",
            min: 0.0,
            max: 24.0,
            default: 6.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B1Makeup,
            name: "Band 1 Makeup",
            module: "Band 1",
            min: -24.0,
            max: 24.0,
            default: 0.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B2Threshold,
            name: "Band 2 Threshold",
            module: "Band 2",
            min: -52.5,
            max: 30.0,
            default: -3.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B2Ratio,
            name: "Band 2 Ratio",
            module: "Band 2",
            min: 1.0,
            max: 100.0,
            default: 1.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B2Attack,
            name: "Band 2 Attack",
            module: "Band 2",
            min: 0.0,
            max: 2000.0,
            default: 20.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B2Release,
            name: "Band 2 Release",
            module: "Band 2",
            min: 0.0,
            max: 5000.0,
            default: 100.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B2Knee,
            name: "Band 2 Knee",
            module: "Band 2",
            min: 0.0,
            max: 24.0,
            default: 6.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B2Makeup,
            name: "Band 2 Makeup",
            module: "Band 2",
            min: -24.0,
            max: 24.0,
            default: 0.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B3Threshold,
            name: "Band 3 Threshold",
            module: "Band 3",
            min: -52.5,
            max: 30.0,
            default: -3.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B3Ratio,
            name: "Band 3 Ratio",
            module: "Band 3",
            min: 1.0,
            max: 100.0,
            default: 4.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B3Attack,
            name: "Band 3 Attack",
            module: "Band 3",
            min: 0.0,
            max: 2000.0,
            default: 20.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B3Release,
            name: "Band 3 Release",
            module: "Band 3",
            min: 0.0,
            max: 5000.0,
            default: 100.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B3Knee,
            name: "Band 3 Knee",
            module: "Band 3",
            min: 0.0,
            max: 24.0,
            default: 6.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B3Makeup,
            name: "Band 3 Makeup",
            module: "Band 3",
            min: -24.0,
            max: 24.0,
            default: 0.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B4Threshold,
            name: "Band 4 Threshold",
            module: "Band 4",
            min: -52.5,
            max: 30.0,
            default: -3.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B4Ratio,
            name: "Band 4 Ratio",
            module: "Band 4",
            min: 1.0,
            max: 100.0,
            default: 4.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B4Attack,
            name: "Band 4 Attack",
            module: "Band 4",
            min: 0.0,
            max: 2000.0,
            default: 20.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B4Release,
            name: "Band 4 Release",
            module: "Band 4",
            min: 0.0,
            max: 5000.0,
            default: 100.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B4Knee,
            name: "Band 4 Knee",
            module: "Band 4",
            min: 0.0,
            max: 24.0,
            default: 6.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B4Makeup,
            name: "Band 4 Makeup",
            module: "Band 4",
            min: -24.0,
            max: 24.0,
            default: 0.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::Mode,
            name: "Mode",
            module: "Compressor",
            min: 0.0,
            max: 1.0,
            default: 0.0,
            step: 1.0,
            flags: ENUM_FLAGS,
        }
        {
            id: ParamId::Lookahead,
            name: "Lookahead",
            module: "Compressor",
            min: 0.0,
            max: 20.0,
            default: 0.0,
            step: 0.01,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::ScBoost,
            name: "SC Boost",
            module: "Sidechain",
            min: 0.0,
            max: 4.0,
            default: 0.0,
            step: 1.0,
            flags: ENUM_FLAGS,
        }
        {
            id: ParamId::Topology,
            name: "Topology",
            module: "Compressor",
            min: 0.0,
            max: 1.0,
            default: 1.0,
            step: 1.0,
            flags: ENUM_FLAGS,
        }
        {
            id: ParamId::Channels,
            name: "Channels",
            module: "Global",
            min: 1.0,
            max: 2.0,
            default: 1.0,
            step: 1.0,
            flags: BOOL_FLAGS,
        }
        {
            id: ParamId::B1Range,
            name: "Band 1 Range",
            module: "Band 1",
            min: -30.0,
            max: 30.0,
            default: -12.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B2Range,
            name: "Band 2 Range",
            module: "Band 2",
            min: -30.0,
            max: 30.0,
            default: -12.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B3Range,
            name: "Band 3 Range",
            module: "Band 3",
            min: -30.0,
            max: 30.0,
            default: -12.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B4Range,
            name: "Band 4 Range",
            module: "Band 4",
            min: -30.0,
            max: 30.0,
            default: -12.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::Split4,
            name: "Split 4",
            module: "Crossover",
            min: 20.0,
            max: 20_000.0,
            default: 10_000.0,
            step: 1.0,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::Split5,
            name: "Split 5",
            module: "Crossover",
            min: 20.0,
            max: 20_000.0,
            default: 14_000.0,
            step: 1.0,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::BandCount,
            name: "Band Count",
            module: "Crossover",
            min: 1.0,
            max: 6.0,
            default: 1.0,
            step: 1.0,
            flags: AUTOMATABLE | CLAP_PARAM_IS_STEPPED,
        }
        {
            id: ParamId::B5Threshold,
            name: "Band 5 Threshold",
            module: "Band 5",
            min: -52.5,
            max: 30.0,
            default: -3.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B5Ratio,
            name: "Band 5 Ratio",
            module: "Band 5",
            min: 1.0,
            max: 100.0,
            default: 4.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B5Attack,
            name: "Band 5 Attack",
            module: "Band 5",
            min: 0.0,
            max: 2000.0,
            default: 20.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B5Release,
            name: "Band 5 Release",
            module: "Band 5",
            min: 0.0,
            max: 5000.0,
            default: 100.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B5Knee,
            name: "Band 5 Knee",
            module: "Band 5",
            min: 0.0,
            max: 24.0,
            default: 6.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B5Makeup,
            name: "Band 5 Makeup",
            module: "Band 5",
            min: -24.0,
            max: 24.0,
            default: 0.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B5Range,
            name: "Band 5 Range",
            module: "Band 5",
            min: -30.0,
            max: 30.0,
            default: -12.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B6Threshold,
            name: "Band 6 Threshold",
            module: "Band 6",
            min: -52.5,
            max: 30.0,
            default: -3.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B6Ratio,
            name: "Band 6 Ratio",
            module: "Band 6",
            min: 1.0,
            max: 100.0,
            default: 4.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B6Attack,
            name: "Band 6 Attack",
            module: "Band 6",
            min: 0.0,
            max: 2000.0,
            default: 20.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B6Release,
            name: "Band 6 Release",
            module: "Band 6",
            min: 0.0,
            max: 5000.0,
            default: 100.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B6Knee,
            name: "Band 6 Knee",
            module: "Band 6",
            min: 0.0,
            max: 24.0,
            default: 6.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B6Makeup,
            name: "Band 6 Makeup",
            module: "Band 6",
            min: -24.0,
            max: 24.0,
            default: 0.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
        {
            id: ParamId::B6Range,
            name: "Band 6 Range",
            module: "Band 6",
            min: -30.0,
            max: 30.0,
            default: -12.0,
            step: 0.1,
            flags: AUTOMATABLE,
        }
    ];
}

const AUTOMATABLE: u32 = CLAP_PARAM_IS_AUTOMATABLE | CLAP_PARAM_REQUIRES_PROCESS;
const BOOL_FLAGS: u32 = AUTOMATABLE | CLAP_PARAM_IS_STEPPED;
const ENUM_FLAGS: u32 = AUTOMATABLE | CLAP_PARAM_IS_STEPPED | CLAP_PARAM_IS_ENUM;
