use std::sync::atomic::{AtomicBool, AtomicU64, Ordering};

use clap_clap::ffi::{
    CLAP_PARAM_IS_AUTOMATABLE, CLAP_PARAM_IS_STEPPED, CLAP_PARAM_REQUIRES_PROCESS,
};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u16)]
pub enum ParamId {
    InputGain = 0,
    OutputGain = 1,
    ParametricBypass = 2,
    GraphicBypass = 3,
    Para1Freq = 4,
    Para1Gain = 5,
    Para1Q = 6,
    Para2Freq = 7,
    Para2Gain = 8,
    Para2Q = 9,
    Para3Freq = 10,
    Para3Gain = 11,
    Para3Q = 12,
    Para4Freq = 13,
    Para4Gain = 14,
    Para4Q = 15,
    Para5Freq = 16,
    Para5Gain = 17,
    Para5Q = 18,
    Para6Freq = 19,
    Para6Gain = 20,
    Para6Q = 21,
    Para7Freq = 22,
    Para7Gain = 23,
    Para7Q = 24,
    Para8Freq = 25,
    Para8Gain = 26,
    Para8Q = 27,
    Para9Freq = 28,
    Para9Gain = 29,
    Para9Q = 30,
    Para10Freq = 31,
    Para10Gain = 32,
    Para10Q = 33,
    Para11Freq = 34,
    Para11Gain = 35,
    Para11Q = 36,
    Para12Freq = 37,
    Para12Gain = 38,
    Para12Q = 39,
    Para13Freq = 40,
    Para13Gain = 41,
    Para13Q = 42,
    Para14Freq = 43,
    Para14Gain = 44,
    Para14Q = 45,
    Para15Freq = 46,
    Para15Gain = 47,
    Para15Q = 48,
    Para16Freq = 49,
    Para16Gain = 50,
    Para16Q = 51,
    Para17Freq = 52,
    Para17Gain = 53,
    Para17Q = 54,
    Para18Freq = 55,
    Para18Gain = 56,
    Para18Q = 57,
    Para19Freq = 58,
    Para19Gain = 59,
    Para19Q = 60,
    Para20Freq = 61,
    Para20Gain = 62,
    Para20Q = 63,
    Para21Freq = 64,
    Para21Gain = 65,
    Para21Q = 66,
    Para22Freq = 67,
    Para22Gain = 68,
    Para22Q = 69,
    Para23Freq = 70,
    Para23Gain = 71,
    Para23Q = 72,
    Para24Freq = 73,
    Para24Gain = 74,
    Para24Q = 75,
    Para25Freq = 76,
    Para25Gain = 77,
    Para25Q = 78,
    Para26Freq = 79,
    Para26Gain = 80,
    Para26Q = 81,
    Para27Freq = 82,
    Para27Gain = 83,
    Para27Q = 84,
    Para28Freq = 85,
    Para28Gain = 86,
    Para28Q = 87,
    Para29Freq = 88,
    Para29Gain = 89,
    Para29Q = 90,
    Para30Freq = 91,
    Para30Gain = 92,
    Para30Q = 93,
    Para31Freq = 94,
    Para31Gain = 95,
    Para31Q = 96,
    Para32Freq = 97,
    Para32Gain = 98,
    Para32Q = 99,
    Graphic1Gain = 100,
    Graphic2Gain = 101,
    Graphic3Gain = 102,
    Graphic4Gain = 103,
    Graphic5Gain = 104,
    Graphic6Gain = 105,
    Graphic7Gain = 106,
    Graphic8Gain = 107,
    Graphic9Gain = 108,
    Graphic10Gain = 109,
    Graphic11Gain = 110,
    Graphic12Gain = 111,
    Graphic13Gain = 112,
    Graphic14Gain = 113,
    Graphic15Gain = 114,
    Graphic16Gain = 115,
    Graphic17Gain = 116,
    Graphic18Gain = 117,
    Graphic19Gain = 118,
    Graphic20Gain = 119,
    Graphic21Gain = 120,
    Graphic22Gain = 121,
    Graphic23Gain = 122,
    Graphic24Gain = 123,
    Graphic25Gain = 124,
    Graphic26Gain = 125,
    Graphic27Gain = 126,
    Graphic28Gain = 127,
    Graphic29Gain = 128,
    Graphic30Gain = 129,
    Graphic31Gain = 130,
    Graphic32Gain = 131,
}

impl ParamId {
    pub const COUNT: usize = 132;

    pub const fn as_index(self) -> usize {
        self as usize
    }

    pub fn from_raw(id: u32) -> Option<Self> {
        if id < Self::COUNT as u32 {
            Some(unsafe { std::mem::transmute::<u16, ParamId>(id as u16) })
        } else {
            None
        }
    }

    pub const fn all() -> [ParamId; Self::COUNT] {
        [
            ParamId::InputGain,
            ParamId::OutputGain,
            ParamId::ParametricBypass,
            ParamId::GraphicBypass,
            ParamId::Para1Freq,
            ParamId::Para1Gain,
            ParamId::Para1Q,
            ParamId::Para2Freq,
            ParamId::Para2Gain,
            ParamId::Para2Q,
            ParamId::Para3Freq,
            ParamId::Para3Gain,
            ParamId::Para3Q,
            ParamId::Para4Freq,
            ParamId::Para4Gain,
            ParamId::Para4Q,
            ParamId::Para5Freq,
            ParamId::Para5Gain,
            ParamId::Para5Q,
            ParamId::Para6Freq,
            ParamId::Para6Gain,
            ParamId::Para6Q,
            ParamId::Para7Freq,
            ParamId::Para7Gain,
            ParamId::Para7Q,
            ParamId::Para8Freq,
            ParamId::Para8Gain,
            ParamId::Para8Q,
            ParamId::Para9Freq,
            ParamId::Para9Gain,
            ParamId::Para9Q,
            ParamId::Para10Freq,
            ParamId::Para10Gain,
            ParamId::Para10Q,
            ParamId::Para11Freq,
            ParamId::Para11Gain,
            ParamId::Para11Q,
            ParamId::Para12Freq,
            ParamId::Para12Gain,
            ParamId::Para12Q,
            ParamId::Para13Freq,
            ParamId::Para13Gain,
            ParamId::Para13Q,
            ParamId::Para14Freq,
            ParamId::Para14Gain,
            ParamId::Para14Q,
            ParamId::Para15Freq,
            ParamId::Para15Gain,
            ParamId::Para15Q,
            ParamId::Para16Freq,
            ParamId::Para16Gain,
            ParamId::Para16Q,
            ParamId::Para17Freq,
            ParamId::Para17Gain,
            ParamId::Para17Q,
            ParamId::Para18Freq,
            ParamId::Para18Gain,
            ParamId::Para18Q,
            ParamId::Para19Freq,
            ParamId::Para19Gain,
            ParamId::Para19Q,
            ParamId::Para20Freq,
            ParamId::Para20Gain,
            ParamId::Para20Q,
            ParamId::Para21Freq,
            ParamId::Para21Gain,
            ParamId::Para21Q,
            ParamId::Para22Freq,
            ParamId::Para22Gain,
            ParamId::Para22Q,
            ParamId::Para23Freq,
            ParamId::Para23Gain,
            ParamId::Para23Q,
            ParamId::Para24Freq,
            ParamId::Para24Gain,
            ParamId::Para24Q,
            ParamId::Para25Freq,
            ParamId::Para25Gain,
            ParamId::Para25Q,
            ParamId::Para26Freq,
            ParamId::Para26Gain,
            ParamId::Para26Q,
            ParamId::Para27Freq,
            ParamId::Para27Gain,
            ParamId::Para27Q,
            ParamId::Para28Freq,
            ParamId::Para28Gain,
            ParamId::Para28Q,
            ParamId::Para29Freq,
            ParamId::Para29Gain,
            ParamId::Para29Q,
            ParamId::Para30Freq,
            ParamId::Para30Gain,
            ParamId::Para30Q,
            ParamId::Para31Freq,
            ParamId::Para31Gain,
            ParamId::Para31Q,
            ParamId::Para32Freq,
            ParamId::Para32Gain,
            ParamId::Para32Q,
            ParamId::Graphic1Gain,
            ParamId::Graphic2Gain,
            ParamId::Graphic3Gain,
            ParamId::Graphic4Gain,
            ParamId::Graphic5Gain,
            ParamId::Graphic6Gain,
            ParamId::Graphic7Gain,
            ParamId::Graphic8Gain,
            ParamId::Graphic9Gain,
            ParamId::Graphic10Gain,
            ParamId::Graphic11Gain,
            ParamId::Graphic12Gain,
            ParamId::Graphic13Gain,
            ParamId::Graphic14Gain,
            ParamId::Graphic15Gain,
            ParamId::Graphic16Gain,
            ParamId::Graphic17Gain,
            ParamId::Graphic18Gain,
            ParamId::Graphic19Gain,
            ParamId::Graphic20Gain,
            ParamId::Graphic21Gain,
            ParamId::Graphic22Gain,
            ParamId::Graphic23Gain,
            ParamId::Graphic24Gain,
            ParamId::Graphic25Gain,
            ParamId::Graphic26Gain,
            ParamId::Graphic27Gain,
            ParamId::Graphic28Gain,
            ParamId::Graphic29Gain,
            ParamId::Graphic30Gain,
            ParamId::Graphic31Gain,
            ParamId::Graphic32Gain,
        ]
    }

    pub fn para_freq(index: usize) -> Self {
        let raw = 4 + index * 3;
        Self::from_raw(raw as u32).unwrap_or(Self::Para1Freq)
    }

    pub fn para_gain(index: usize) -> Self {
        let raw = 5 + index * 3;
        Self::from_raw(raw as u32).unwrap_or(Self::Para1Gain)
    }

    pub fn para_q(index: usize) -> Self {
        let raw = 6 + index * 3;
        Self::from_raw(raw as u32).unwrap_or(Self::Para1Q)
    }

    pub fn graphic_gain(index: usize) -> Self {
        let raw = 100 + index;
        Self::from_raw(raw as u32).unwrap_or(Self::Graphic1Gain)
    }
}

#[derive(Debug, Clone, Copy)]
pub struct ParamDef {
    pub id: ParamId,
    pub name: &'static str,
    pub module: &'static str,
    pub min: f64,
    pub max: f64,
    pub default: f64,
    pub step: f64,
    pub flags: u32,
}

const AUTOMATABLE: u32 = CLAP_PARAM_IS_AUTOMATABLE | CLAP_PARAM_REQUIRES_PROCESS;
const STEPPED_BOOL: u32 = AUTOMATABLE | CLAP_PARAM_IS_STEPPED;

pub const PARAMS: [ParamDef; ParamId::COUNT] = [
    ParamDef {
        id: ParamId::InputGain,
        name: "Input Gain",
        module: "Global",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::OutputGain,
        name: "Output Gain",
        module: "Global",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::ParametricBypass,
        name: "Parametric Bypass",
        module: "Parametric",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 1.0,
        flags: STEPPED_BOOL,
    },
    ParamDef {
        id: ParamId::GraphicBypass,
        name: "Graphic Bypass",
        module: "Graphic",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 1.0,
        flags: STEPPED_BOOL,
    },
    ParamDef {
        id: ParamId::Para1Freq,
        name: "P1 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para1Gain,
        name: "P1 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para1Q,
        name: "P1 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para2Freq,
        name: "P2 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para2Gain,
        name: "P2 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para2Q,
        name: "P2 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para3Freq,
        name: "P3 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para3Gain,
        name: "P3 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para3Q,
        name: "P3 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para4Freq,
        name: "P4 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para4Gain,
        name: "P4 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para4Q,
        name: "P4 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para5Freq,
        name: "P5 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para5Gain,
        name: "P5 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para5Q,
        name: "P5 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para6Freq,
        name: "P6 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para6Gain,
        name: "P6 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para6Q,
        name: "P6 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para7Freq,
        name: "P7 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para7Gain,
        name: "P7 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para7Q,
        name: "P7 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para8Freq,
        name: "P8 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para8Gain,
        name: "P8 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para8Q,
        name: "P8 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para9Freq,
        name: "P9 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para9Gain,
        name: "P9 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para9Q,
        name: "P9 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para10Freq,
        name: "P10 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para10Gain,
        name: "P10 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para10Q,
        name: "P10 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para11Freq,
        name: "P11 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para11Gain,
        name: "P11 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para11Q,
        name: "P11 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para12Freq,
        name: "P12 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para12Gain,
        name: "P12 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para12Q,
        name: "P12 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para13Freq,
        name: "P13 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para13Gain,
        name: "P13 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para13Q,
        name: "P13 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para14Freq,
        name: "P14 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para14Gain,
        name: "P14 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para14Q,
        name: "P14 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para15Freq,
        name: "P15 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para15Gain,
        name: "P15 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para15Q,
        name: "P15 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para16Freq,
        name: "P16 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para16Gain,
        name: "P16 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para16Q,
        name: "P16 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para17Freq,
        name: "P17 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para17Gain,
        name: "P17 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para17Q,
        name: "P17 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para18Freq,
        name: "P18 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para18Gain,
        name: "P18 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para18Q,
        name: "P18 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para19Freq,
        name: "P19 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para19Gain,
        name: "P19 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para19Q,
        name: "P19 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para20Freq,
        name: "P20 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para20Gain,
        name: "P20 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para20Q,
        name: "P20 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para21Freq,
        name: "P21 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para21Gain,
        name: "P21 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para21Q,
        name: "P21 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para22Freq,
        name: "P22 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para22Gain,
        name: "P22 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para22Q,
        name: "P22 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para23Freq,
        name: "P23 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para23Gain,
        name: "P23 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para23Q,
        name: "P23 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para24Freq,
        name: "P24 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para24Gain,
        name: "P24 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para24Q,
        name: "P24 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para25Freq,
        name: "P25 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para25Gain,
        name: "P25 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para25Q,
        name: "P25 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para26Freq,
        name: "P26 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para26Gain,
        name: "P26 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para26Q,
        name: "P26 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para27Freq,
        name: "P27 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para27Gain,
        name: "P27 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para27Q,
        name: "P27 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para28Freq,
        name: "P28 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para28Gain,
        name: "P28 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para28Q,
        name: "P28 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para29Freq,
        name: "P29 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para29Gain,
        name: "P29 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para29Q,
        name: "P29 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para30Freq,
        name: "P30 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para30Gain,
        name: "P30 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para30Q,
        name: "P30 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para31Freq,
        name: "P31 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para31Gain,
        name: "P31 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para31Q,
        name: "P31 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para32Freq,
        name: "P32 Freq",
        module: "Parametric",
        min: 20.0,
        max: 20000.0,
        default: 1000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para32Gain,
        name: "P32 Gain",
        module: "Parametric",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Para32Q,
        name: "P32 Q",
        module: "Parametric",
        min: 0.1,
        max: 24.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic1Gain,
        name: "G1 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic2Gain,
        name: "G2 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic3Gain,
        name: "G3 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic4Gain,
        name: "G4 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic5Gain,
        name: "G5 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic6Gain,
        name: "G6 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic7Gain,
        name: "G7 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic8Gain,
        name: "G8 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic9Gain,
        name: "G9 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic10Gain,
        name: "G10 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic11Gain,
        name: "G11 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic12Gain,
        name: "G12 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic13Gain,
        name: "G13 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic14Gain,
        name: "G14 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic15Gain,
        name: "G15 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic16Gain,
        name: "G16 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic17Gain,
        name: "G17 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic18Gain,
        name: "G18 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic19Gain,
        name: "G19 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic20Gain,
        name: "G20 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic21Gain,
        name: "G21 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic22Gain,
        name: "G22 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic23Gain,
        name: "G23 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic24Gain,
        name: "G24 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic25Gain,
        name: "G25 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic26Gain,
        name: "G26 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic27Gain,
        name: "G27 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic28Gain,
        name: "G28 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic29Gain,
        name: "G29 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic30Gain,
        name: "G30 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic31Gain,
        name: "G31 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamDef {
        id: ParamId::Graphic32Gain,
        name: "G32 Gain",
        module: "Graphic",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
];

pub fn sanitize_param_value(id: ParamId, value: f64) -> f64 {
    let def = PARAMS[id.as_index()];
    let clamped = value.clamp(def.min, def.max);
    if def.step > 0.0 {
        let ticks = ((clamped - def.min) / def.step).round();
        (def.min + ticks * def.step).clamp(def.min, def.max)
    } else {
        clamped
    }
}

#[derive(Debug)]
pub struct ParamStore {
    values: [AtomicU64; ParamId::COUNT],
    dirty: AtomicBool,
}

impl Default for ParamStore {
    fn default() -> Self {
        Self {
            values: PARAMS.map(|param| AtomicU64::new(param.default.to_bits())),
            dirty: AtomicBool::new(false),
        }
    }
}

impl ParamStore {
    pub fn get(&self, id: ParamId) -> f64 {
        f64::from_bits(self.values[id.as_index()].load(Ordering::Acquire))
    }

    pub fn set(&self, id: ParamId, value: f64) {
        self.values[id.as_index()].store(value.to_bits(), Ordering::Release);
        self.dirty.store(true, Ordering::Release);
    }

    pub fn get_bool(&self, id: ParamId) -> bool {
        self.get(id) >= 0.5
    }
}
