//! Parameter definitions for Maolan Kick.
//!
//! Exposes 2,864 automatable parameters (179 types × 16 instruments).
//! ParamId is a computed u32: bits 0-7 = param type, bits 8-11 = instrument index.

use std::sync::atomic::{AtomicU64, Ordering};

use clap_clap::ffi::{
    CLAP_PARAM_IS_AUTOMATABLE, CLAP_PARAM_IS_ENUM, CLAP_PARAM_IS_STEPPED,
    CLAP_PARAM_REQUIRES_PROCESS,
};

pub const PARAM_TYPES_PER_INSTRUMENT: usize = 179;
pub const INSTRUMENT_COUNT: usize = 16;
pub const TOTAL_PARAM_COUNT: usize = PARAM_TYPES_PER_INSTRUMENT * INSTRUMENT_COUNT;

// ---------------------------------------------------------------------------
// ParamType — the 179 parameter types (one set per instrument)
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
#[repr(u8)]
pub enum ParamType {
    HumanizerVelocity = 0,
    HumanizerTiming = 1,
    ActiveInstrument = 2,
    MasterLength = 3,
    MasterOutputGain = 4,
    MasterNoteOffDecay = 5,
    MasterNoteOffEnabled = 6,
    MasterPitchToNote = 7,
    MasterKeyMin = 8,
    MasterKeyMax = 9,
    MasterMidiChannel = 10,
    MasterMuted = 11,
    MasterSoloed = 12,
    MasterFilterType = 13,
    MasterFilterCutoff = 14,
    MasterFilterQ = 15,
    MasterDistortionType = 16,
    MasterDistortionDrive = 17,
    MasterDistortionInputLimit = 18,
    MasterDistortionOutputLimit = 19,
    MasterDistortionVolEnvAttack = 20,
    MasterDistortionVolEnvDecay = 21,
    MasterDistortionVolEnvSustain = 22,
    MasterDistortionVolEnvRelease = 23,
    MasterLimiterThreshold = 24,
    MasterLimiterRelease = 25,
    MasterGlobalAmpEnvAttack = 26,
    MasterGlobalAmpEnvDecay = 27,
    MasterGlobalAmpEnvSustain = 28,
    MasterGlobalAmpEnvRelease = 29,
    Layer0Enabled = 30,
    Layer0Amp = 31,
    Layer0FilterType = 32,
    Layer0FilterCutoff = 33,
    Layer0FilterQ = 34,
    Layer0DistortionType = 35,
    Layer0DistortionDrive = 36,
    Layer0DistortionVolEnvAttack = 37,
    Layer0DistortionVolEnvDecay = 38,
    Layer0DistortionVolEnvSustain = 39,
    Layer0DistortionVolEnvRelease = 40,
    Layer0FmRouting0 = 41,
    Layer0FmRouting1 = 42,
    Layer0FmRouting2 = 43,
    Layer1Enabled = 44,
    Layer1Amp = 45,
    Layer2Enabled = 46,
    Layer2Amp = 47,
    Osc0Waveform = 48,
    Osc0Freq = 49,
    Osc0Amp = 50,
    Osc0Phase = 51,
    Osc0FmAmount = 52,
    Osc0FilterType = 53,
    Osc0FilterCutoff = 54,
    Osc0FilterQ = 55,
    Osc0DistortionType = 56,
    Osc0DistortionDrive = 57,
    Osc0DistortionVolEnvAttack = 58,
    Osc0DistortionVolEnvDecay = 59,
    Osc0DistortionVolEnvSustain = 60,
    Osc0DistortionVolEnvRelease = 61,
    Osc0FilterCutoffEnvAttack = 62,
    Osc0FilterCutoffEnvDecay = 63,
    Osc0FilterCutoffEnvSustain = 64,
    Osc0FilterCutoffEnvRelease = 65,
    Osc0FilterQEnvAttack = 66,
    Osc0FilterQEnvDecay = 67,
    Osc0FilterQEnvSustain = 68,
    Osc0FilterQEnvRelease = 69,
    Osc0DistortionDriveEnvAttack = 70,
    Osc0DistortionDriveEnvDecay = 71,
    Osc0DistortionDriveEnvSustain = 72,
    Osc0DistortionDriveEnvRelease = 73,
    Osc0PitchShiftEnvAttack = 74,
    Osc0PitchShiftEnvDecay = 75,
    Osc0PitchShiftEnvSustain = 76,
    Osc0PitchShiftEnvRelease = 77,
    Osc0FreqEnvAttack = 78,
    Osc0FreqEnvDecay = 79,
    Osc0FreqEnvSustain = 80,
    Osc0FreqEnvRelease = 81,
    Osc0FreqEnvMode = 82,
    Osc0AmpEnvAttack = 83,
    Osc0AmpEnvDecay = 84,
    Osc0AmpEnvSustain = 85,
    Osc0AmpEnvRelease = 86,
    Osc1Waveform = 87,
    Osc1Freq = 88,
    Osc1Amp = 89,
    Osc1Phase = 90,
    Osc1FmAmount = 91,
    Osc1FilterType = 92,
    Osc1FilterCutoff = 93,
    Osc1FilterQ = 94,
    Osc1DistortionType = 95,
    Osc1DistortionDrive = 96,
    Osc1DistortionVolEnvAttack = 97,
    Osc1DistortionVolEnvDecay = 98,
    Osc1DistortionVolEnvSustain = 99,
    Osc1DistortionVolEnvRelease = 100,
    Osc1FilterCutoffEnvAttack = 101,
    Osc1FilterCutoffEnvDecay = 102,
    Osc1FilterCutoffEnvSustain = 103,
    Osc1FilterCutoffEnvRelease = 104,
    Osc1FilterQEnvAttack = 105,
    Osc1FilterQEnvDecay = 106,
    Osc1FilterQEnvSustain = 107,
    Osc1FilterQEnvRelease = 108,
    Osc1DistortionDriveEnvAttack = 109,
    Osc1DistortionDriveEnvDecay = 110,
    Osc1DistortionDriveEnvSustain = 111,
    Osc1DistortionDriveEnvRelease = 112,
    Osc1PitchShiftEnvAttack = 113,
    Osc1PitchShiftEnvDecay = 114,
    Osc1PitchShiftEnvSustain = 115,
    Osc1PitchShiftEnvRelease = 116,
    Osc1FreqEnvAttack = 117,
    Osc1FreqEnvDecay = 118,
    Osc1FreqEnvSustain = 119,
    Osc1FreqEnvRelease = 120,
    Osc1FreqEnvMode = 121,
    Osc1AmpEnvAttack = 122,
    Osc1AmpEnvDecay = 123,
    Osc1AmpEnvSustain = 124,
    Osc1AmpEnvRelease = 125,
    Osc2Waveform = 126,
    Osc2Freq = 127,
    Osc2Amp = 128,
    Osc2Phase = 129,
    Osc2FmAmount = 130,
    Osc2FilterType = 131,
    Osc2FilterCutoff = 132,
    Osc2FilterQ = 133,
    Osc2DistortionType = 134,
    Osc2DistortionDrive = 135,
    Osc2DistortionVolEnvAttack = 136,
    Osc2DistortionVolEnvDecay = 137,
    Osc2DistortionVolEnvSustain = 138,
    Osc2DistortionVolEnvRelease = 139,
    Osc2FilterCutoffEnvAttack = 140,
    Osc2FilterCutoffEnvDecay = 141,
    Osc2FilterCutoffEnvSustain = 142,
    Osc2FilterCutoffEnvRelease = 143,
    Osc2FilterQEnvAttack = 144,
    Osc2FilterQEnvDecay = 145,
    Osc2FilterQEnvSustain = 146,
    Osc2FilterQEnvRelease = 147,
    Osc2DistortionDriveEnvAttack = 148,
    Osc2DistortionDriveEnvDecay = 149,
    Osc2DistortionDriveEnvSustain = 150,
    Osc2DistortionDriveEnvRelease = 151,
    Osc2PitchShiftEnvAttack = 152,
    Osc2PitchShiftEnvDecay = 153,
    Osc2PitchShiftEnvSustain = 154,
    Osc2PitchShiftEnvRelease = 155,
    Osc2FreqEnvAttack = 156,
    Osc2FreqEnvDecay = 157,
    Osc2FreqEnvSustain = 158,
    Osc2FreqEnvRelease = 159,
    Osc2FreqEnvMode = 160,
    Osc2AmpEnvAttack = 161,
    Osc2AmpEnvDecay = 162,
    Osc2AmpEnvSustain = 163,
    Osc2AmpEnvRelease = 164,
    NoiseType = 165,
    NoiseAmp = 166,
    NoiseDensity = 167,
    NoiseFilterType = 168,
    NoiseFilterCutoff = 169,
    NoiseFilterQ = 170,
    NoiseAmpEnvAttack = 171,
    NoiseAmpEnvDecay = 172,
    NoiseAmpEnvSustain = 173,
    NoiseAmpEnvRelease = 174,
    NoiseDensityEnvAttack = 175,
    NoiseDensityEnvDecay = 176,
    NoiseDensityEnvSustain = 177,
    NoiseDensityEnvRelease = 178,
}

impl ParamType {
    pub const COUNT: usize = 179;

    pub fn from_raw(v: u8) -> Option<Self> {
        if v < Self::COUNT as u8 {
            Some(unsafe { std::mem::transmute::<u8, ParamType>(v) })
        } else {
            None
        }
    }

    pub fn as_index(self) -> usize {
        self as usize
    }
}

// ---------------------------------------------------------------------------
// ParamId — computed u32: (instrument << 8) | param_type
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord, Hash)]
pub struct ParamId(pub u32);

impl ParamId {
    pub const COUNT: usize = TOTAL_PARAM_COUNT;

    #[inline]
    pub const fn new(instrument: u8, param_type: ParamType) -> Self {
        Self((instrument as u32) * (ParamType::COUNT as u32) + (param_type as u32))
    }

    #[inline]
    pub const fn instrument(self) -> u8 {
        (self.0 / (ParamType::COUNT as u32)) as u8
    }

    #[inline]
    pub const fn param_type(self) -> ParamType {
        let idx = (self.0 % (ParamType::COUNT as u32)) as u8;
        // Safe because idx is always < ParamType::COUNT
        unsafe { std::mem::transmute(idx) }
    }

    #[inline]
    pub const fn as_index(self) -> usize {
        self.0 as usize
    }

    #[inline]
    pub fn from_raw(id: u32) -> Option<Self> {
        if id < Self::COUNT as u32 {
            Some(Self(id))
        } else {
            None
        }
    }

    #[inline]
    pub const fn from_index(index: usize) -> Option<Self> {
        if index < Self::COUNT {
            Some(Self(index as u32))
        } else {
            None
        }
    }

    /// Iterate all parameter IDs.
    pub fn all() -> impl Iterator<Item = Self> {
        (0..Self::COUNT as u32).map(Self)
    }
}

// ---------------------------------------------------------------------------
// ParamTypeDef — base definition for each of the 179 param types
// ---------------------------------------------------------------------------

#[derive(Debug, Clone, Copy)]
pub struct ParamTypeDef {
    pub base_name: &'static str,
    pub base_module: &'static str,
    pub min: f64,
    pub max: f64,
    pub default: f64,
    pub step: f64,
    pub flags: u32,
}

const AUTOMATABLE: u32 = CLAP_PARAM_IS_AUTOMATABLE | CLAP_PARAM_REQUIRES_PROCESS;
const ENUM: u32 = CLAP_PARAM_IS_ENUM
    | CLAP_PARAM_IS_STEPPED
    | CLAP_PARAM_IS_AUTOMATABLE
    | CLAP_PARAM_REQUIRES_PROCESS;
const TOGGLE: u32 = CLAP_PARAM_IS_STEPPED | CLAP_PARAM_IS_AUTOMATABLE | CLAP_PARAM_REQUIRES_PROCESS;

pub const PARAM_TYPE_DEFS: [ParamTypeDef; ParamType::COUNT] = [
    ParamTypeDef {
        base_name: "Humanizer Velocity",
        base_module: "Kit",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Humanizer Timing",
        base_module: "Kit",
        min: 0.0,
        max: 50.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Active Instrument",
        base_module: "Kit",
        min: 0.0,
        max: 15.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Length",
        base_module: "Master",
        min: 10.0,
        max: 4000.0,
        default: 300.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Output Gain",
        base_module: "Master",
        min: -24.0,
        max: 24.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Note-Off Decay",
        base_module: "Master",
        min: 0.0,
        max: 500.0,
        default: 30.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Note-Off Enabled",
        base_module: "Master",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 1.0,
        flags: TOGGLE,
    },
    ParamTypeDef {
        base_name: "Pitch to Note",
        base_module: "Master",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 1.0,
        flags: TOGGLE,
    },
    ParamTypeDef {
        base_name: "Key Min",
        base_module: "Master",
        min: 0.0,
        max: 127.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Key Max",
        base_module: "Master",
        min: 0.0,
        max: 127.0,
        default: 127.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "MIDI Channel",
        base_module: "Master",
        min: 0.0,
        max: 16.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Muted",
        base_module: "Master",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 1.0,
        flags: TOGGLE,
    },
    ParamTypeDef {
        base_name: "Soloed",
        base_module: "Master",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 1.0,
        flags: TOGGLE,
    },
    ParamTypeDef {
        base_name: "Filter Type",
        base_module: "Master",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Filter Cutoff",
        base_module: "Master",
        min: 20.0,
        max: 20000.0,
        default: 20000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Filter Q",
        base_module: "Master",
        min: 0.01,
        max: 10.0,
        default: 0.7,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Distortion Type",
        base_module: "Master",
        min: 0.0,
        max: 8.0,
        default: 1.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Distortion Drive",
        base_module: "Master",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Dist Input Limit",
        base_module: "Master",
        min: 0.01,
        max: 10.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Dist Output Limit",
        base_module: "Master",
        min: 0.01,
        max: 10.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Dist Vol Attack",
        base_module: "Master",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Dist Vol Decay",
        base_module: "Master",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Dist Vol Sustain",
        base_module: "Master",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Dist Vol Release",
        base_module: "Master",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Limiter Threshold",
        base_module: "Master",
        min: -24.0,
        max: 6.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Limiter Release",
        base_module: "Master",
        min: 1.0,
        max: 500.0,
        default: 50.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Global Amp Attack",
        base_module: "Master",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Global Amp Decay",
        base_module: "Master",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Global Amp Sustain",
        base_module: "Master",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Global Amp Release",
        base_module: "Master",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Layer 0 Enabled",
        base_module: "Layer0",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 1.0,
        flags: TOGGLE,
    },
    ParamTypeDef {
        base_name: "Layer 0 Amp",
        base_module: "Layer0",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Layer 0 Filter Type",
        base_module: "Layer0",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Layer 0 Filter Cutoff",
        base_module: "Layer0",
        min: 20.0,
        max: 20000.0,
        default: 20000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Layer 0 Filter Q",
        base_module: "Layer0",
        min: 0.01,
        max: 10.0,
        default: 0.7,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Layer 0 Dist Type",
        base_module: "Layer0",
        min: 0.0,
        max: 8.0,
        default: 1.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Layer 0 Dist Drive",
        base_module: "Layer0",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "L0 Dist Vol Attack",
        base_module: "Layer0",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "L0 Dist Vol Decay",
        base_module: "Layer0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "L0 Dist Vol Sustain",
        base_module: "Layer0",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "L0 Dist Vol Release",
        base_module: "Layer0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Layer 0 FM Route 0",
        base_module: "Layer0",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Layer 0 FM Route 1",
        base_module: "Layer0",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Layer 0 FM Route 2",
        base_module: "Layer0",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Layer 1 Enabled",
        base_module: "Layer1",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 1.0,
        flags: TOGGLE,
    },
    ParamTypeDef {
        base_name: "Layer 1 Amp",
        base_module: "Layer1",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Layer 2 Enabled",
        base_module: "Layer2",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 1.0,
        flags: TOGGLE,
    },
    ParamTypeDef {
        base_name: "Layer 2 Amp",
        base_module: "Layer2",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 0 Waveform",
        base_module: "Osc0",
        min: 0.0,
        max: 4.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 0 Freq",
        base_module: "Osc0",
        min: 20.0,
        max: 2000.0,
        default: 150.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 0 Amp",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 0.8,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 0 Phase",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 0 FM Amount",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 0 Filter Type",
        base_module: "Osc0",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 0 Filter Cutoff",
        base_module: "Osc0",
        min: 20.0,
        max: 20000.0,
        default: 20000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 0 Filter Q",
        base_module: "Osc0",
        min: 0.01,
        max: 10.0,
        default: 0.7,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 0 Dist Type",
        base_module: "Osc0",
        min: 0.0,
        max: 8.0,
        default: 1.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 0 Dist Drive",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Dist Vol Attack",
        base_module: "Osc0",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Dist Vol Decay",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Dist Vol Sustain",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Dist Vol Release",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Cutoff Attack",
        base_module: "Osc0",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Cutoff Decay",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Cutoff Sustain",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Cutoff Release",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Q Attack",
        base_module: "Osc0",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Q Decay",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Q Sustain",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Q Release",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Drive Attack",
        base_module: "Osc0",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Drive Decay",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Drive Sustain",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Drive Release",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Shift Attack",
        base_module: "Osc0",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Shift Decay",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Shift Sustain",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Shift Release",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Freq Attack",
        base_module: "Osc0",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Freq Decay",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Freq Sustain",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Freq Release",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc0 Freq Mode",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 0 Amp Attack",
        base_module: "Osc0",
        min: 0.0,
        max: 100.0,
        default: 1.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 0 Amp Decay",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 200.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 0 Amp Sustain",
        base_module: "Osc0",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 0 Amp Release",
        base_module: "Osc0",
        min: 1.0,
        max: 1000.0,
        default: 50.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 1 Waveform",
        base_module: "Osc1",
        min: 0.0,
        max: 4.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 1 Freq",
        base_module: "Osc1",
        min: 20.0,
        max: 2000.0,
        default: 150.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 1 Amp",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 1 Phase",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 1 FM Amount",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 1 Filter Type",
        base_module: "Osc1",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 1 Filter Cutoff",
        base_module: "Osc1",
        min: 20.0,
        max: 20000.0,
        default: 20000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 1 Filter Q",
        base_module: "Osc1",
        min: 0.01,
        max: 10.0,
        default: 0.7,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 1 Dist Type",
        base_module: "Osc1",
        min: 0.0,
        max: 8.0,
        default: 1.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 1 Dist Drive",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Dist Vol Attack",
        base_module: "Osc1",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Dist Vol Decay",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Dist Vol Sustain",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Dist Vol Release",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Cutoff Attack",
        base_module: "Osc1",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Cutoff Decay",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Cutoff Sustain",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Cutoff Release",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Q Attack",
        base_module: "Osc1",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Q Decay",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Q Sustain",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Q Release",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Drive Attack",
        base_module: "Osc1",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Drive Decay",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Drive Sustain",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Drive Release",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Shift Attack",
        base_module: "Osc1",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Shift Decay",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Shift Sustain",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Shift Release",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Freq Attack",
        base_module: "Osc1",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Freq Decay",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Freq Sustain",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Freq Release",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc1 Freq Mode",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 1 Amp Attack",
        base_module: "Osc1",
        min: 0.0,
        max: 100.0,
        default: 1.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 1 Amp Decay",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 200.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 1 Amp Sustain",
        base_module: "Osc1",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 1 Amp Release",
        base_module: "Osc1",
        min: 1.0,
        max: 1000.0,
        default: 50.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 2 Waveform",
        base_module: "Osc2",
        min: 0.0,
        max: 4.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 2 Freq",
        base_module: "Osc2",
        min: 20.0,
        max: 2000.0,
        default: 150.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 2 Amp",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 2 Phase",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 2 FM Amount",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 2 Filter Type",
        base_module: "Osc2",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 2 Filter Cutoff",
        base_module: "Osc2",
        min: 20.0,
        max: 20000.0,
        default: 20000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 2 Filter Q",
        base_module: "Osc2",
        min: 0.01,
        max: 10.0,
        default: 0.7,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 2 Dist Type",
        base_module: "Osc2",
        min: 0.0,
        max: 8.0,
        default: 1.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 2 Dist Drive",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Dist Vol Attack",
        base_module: "Osc2",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Dist Vol Decay",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Dist Vol Sustain",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Dist Vol Release",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Cutoff Attack",
        base_module: "Osc2",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Cutoff Decay",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Cutoff Sustain",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Cutoff Release",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Q Attack",
        base_module: "Osc2",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Q Decay",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Q Sustain",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Q Release",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Drive Attack",
        base_module: "Osc2",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Drive Decay",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Drive Sustain",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Drive Release",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Shift Attack",
        base_module: "Osc2",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Shift Decay",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Shift Sustain",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Shift Release",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Freq Attack",
        base_module: "Osc2",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Freq Decay",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Freq Sustain",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Freq Release",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc2 Freq Mode",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Osc 2 Amp Attack",
        base_module: "Osc2",
        min: 0.0,
        max: 100.0,
        default: 1.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 2 Amp Decay",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 200.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 2 Amp Sustain",
        base_module: "Osc2",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Osc 2 Amp Release",
        base_module: "Osc2",
        min: 1.0,
        max: 1000.0,
        default: 50.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Type",
        base_module: "Noise",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Noise Amp",
        base_module: "Noise",
        min: 0.0,
        max: 1.0,
        default: 0.3,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Density",
        base_module: "Noise",
        min: 0.0,
        max: 1.0,
        default: 0.5,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Filter Type",
        base_module: "Noise",
        min: 0.0,
        max: 2.0,
        default: 0.0,
        step: 1.0,
        flags: ENUM,
    },
    ParamTypeDef {
        base_name: "Noise Filter Cutoff",
        base_module: "Noise",
        min: 20.0,
        max: 20000.0,
        default: 8000.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Filter Q",
        base_module: "Noise",
        min: 0.01,
        max: 10.0,
        default: 0.7,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Amp Attack",
        base_module: "Noise",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Amp Decay",
        base_module: "Noise",
        min: 1.0,
        max: 500.0,
        default: 30.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Amp Sustain",
        base_module: "Noise",
        min: 0.0,
        max: 1.0,
        default: 0.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Amp Release",
        base_module: "Noise",
        min: 1.0,
        max: 500.0,
        default: 20.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Density Attack",
        base_module: "Noise",
        min: 0.0,
        max: 100.0,
        default: 0.0,
        step: 0.1,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Density Decay",
        base_module: "Noise",
        min: 1.0,
        max: 500.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Density Sustain",
        base_module: "Noise",
        min: 0.0,
        max: 1.0,
        default: 1.0,
        step: 0.01,
        flags: AUTOMATABLE,
    },
    ParamTypeDef {
        base_name: "Noise Density Release",
        base_module: "Noise",
        min: 1.0,
        max: 500.0,
        default: 0.0,
        step: 1.0,
        flags: AUTOMATABLE,
    },
];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

#[inline]
pub fn param_type_def(param_type: ParamType) -> &'static ParamTypeDef {
    &PARAM_TYPE_DEFS[param_type.as_index()]
}

/// Generate the display name for a parameter, including instrument prefix.
pub fn param_name(id: ParamId) -> String {
    let inst = id.instrument();
    let ty = id.param_type();
    let def = param_type_def(ty);
    format!("Inst {inst} {}", def.base_name)
}

/// State key for serialization. Instrument 0 uses bare base_name for backward compatibility.
pub fn state_key(id: ParamId) -> String {
    let inst = id.instrument();
    let ty = id.param_type();
    let def = param_type_def(ty);
    if inst == 0 {
        def.base_name.to_string()
    } else {
        format!("Inst {inst} {}", def.base_name)
    }
}

pub fn sanitize_param_value(id: ParamId, value: f64) -> f64 {
    let def = param_type_def(id.param_type());
    let clamped = value.clamp(def.min, def.max);
    if def.step > 0.0 {
        let ticks = ((clamped - def.min) / def.step).round();
        (def.min + ticks * def.step).clamp(def.min, def.max)
    } else {
        clamped
    }
}

// ---------------------------------------------------------------------------
// ParamStore
// ---------------------------------------------------------------------------

#[derive(Debug)]
pub struct ParamStore {
    values: Vec<AtomicU64>,
}

impl Default for ParamStore {
    fn default() -> Self {
        let mut values = Vec::with_capacity(TOTAL_PARAM_COUNT);
        for i in 0..TOTAL_PARAM_COUNT {
            let inst = (i / PARAM_TYPES_PER_INSTRUMENT) as u8;
            let ty_idx = i % PARAM_TYPES_PER_INSTRUMENT;
            let def = &PARAM_TYPE_DEFS[ty_idx];
            // For instruments 1-15, copy defaults from instrument 0
            let _ = inst;
            values.push(AtomicU64::new(def.default.to_bits()));
        }
        Self { values }
    }
}

impl ParamStore {
    pub fn get(&self, id: ParamId) -> f64 {
        f64::from_bits(self.values[id.as_index()].load(Ordering::Acquire))
    }

    pub fn set(&self, id: ParamId, value: f64) {
        self.values[id.as_index()].store(value.to_bits(), Ordering::Release);
    }
}

impl crate::common::ClapParamId for ParamId {
    const COUNT: usize = TOTAL_PARAM_COUNT;

    fn as_index(self) -> usize {
        self.as_index()
    }

    fn from_raw(id: u32) -> Option<Self> {
        Self::from_raw(id)
    }
}
